version: '2'
services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    command: redis-server --loglevel verbose --appendonly yes
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

