version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --loglevel verbose --appendonly yes
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
  eurovisionVoting:
    image: deepster/eurovision-voting
    volumes:
      - ./docker/app/conf/production.conf:/usr/config/production.conf
      - ./docker/app/conf/logback.xml:/usr/config/logback.xml
    links:
      - redis:redis
    ports:
      - "8080:80"